theme: jekyll-theme-cayman
title: Hike Lin Personal Blog
description: |
  Base on Financial Technology, 10 years of extensive project experience in enterprise cloud service migration/containerization 
  with high focus on combining EDA and Microservices Architecture to do business primarily design.
  Especially familiar with EJB monolithic system to Microservices decomposition.